llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  azureopenai:
    provider: "azureopenai"
    model_name: "gpt-4o"
    endpoint: "https://srepoc-ai-services.openai.azure.com/"
    api_version: "2025-01-01-preview"