version: "3.9"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./_data/mysql:/var/lib/mysql  # ✅ MySQL data persisted locally

  zenml:
    image: zenmldocker/zenml-server
    ports:
      - "8237:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@host.docker.internal/zenml
      - ZENML_SERVER_JWT_SECRET_KEY="x09a@3sad*Df42ad566bb"
    volumes:
      - ./_data/zenml:/root/.config/zenml  # ✅ Persist ZenML config and token state
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./_data/mlflow:/mlflow          # ✅ Artifact root
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/mlruns
