apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse
  namespace: riskiq
  labels:
    app: langfuse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
        - name: langfuse
          image: aksocpocacr.azurecr.io/langfuse:3.79
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "mysql://root@aksoc-dev-eastus-riskiq-sql.mysql.database.azure.com/riskiq"
            - name: LANGFUSE_DB_URL
              value: "mysql://root@aksoc-dev-eastus-riskiq-sql.mysql.database.azure.com/riskiq"
            - name: CLICKHOUSE_URL
              value: ""  # Force empty or null ClickHouse URL
            # - name: CLIENT_ID
            #   value: "0fa320a0-b0d0-4a51-aa66-ab64f788b665"
            # - name: TENANT_ID
            #   value: "72f988bf-86f1-41af-91ab-2d7cd011db47"
            # - name: REDIRECT_URI
            #   value: "https://srepoc-oauthtest-fmb2d6abdjgpg5ht.b01.azurefd.net/redirect"
            # - name: MANAGED_IDENTITY_CLIENT_ID
            #   value: "e7a6458b-c7a2-4516-83b3-4b292891cb51"
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-service
  namespace: riskiq
spec:
  selector:
    app: langfuse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: langfuse-https-ingress
  namespace: riskiq
spec:
  ingressClassName: nginx
  rules:
  - host: langfuse.cloudblogsaksstg.microsoft.com
    http:
      paths:
      - backend:
          service:
            name: langfuse-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - langfuse.cloudblogsaksstg.microsoft.com
    secretName: riskiq-tls-secret