name: "Deploy Python WebApp"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'projects/python-webapp/**'  # Trigger only when files inside this folder change
  workflow_dispatch:

env:
  CODE_PATH: 'projects/python-webapp'              # Path to your Python app
  AZURE_WEBAPP_NAME: genaiappv1                    # Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'                  # Deployment root
  PYTHON_VERSION: '3.11'                           # Python version
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: ${{ env.CODE_PATH }}
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests (if available)
      working-directory: ${{ env.CODE_PATH }}
      run: |
        source venv/bin/activate
        if [ -f manage.py ]; then
          python manage.py test
        elif [ -f tests/test_app.py ]; then
          pytest tests/
        else
          echo "No tests defined."
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-webapp
        path: ${{ env.CODE_PATH }}
        retention-days: 2

    - name: Upload shared.env
      uses: actions/upload-artifact@v4
      with:
        name: shared-env
        path: .github/env/shared.env
        retention-days: 2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-webapp
        path: .

    - name: Download shared.env
      uses: actions/download-artifact@v4
      with:
        name: shared-env
        path: .github/env

    - name: Export environment variables
      shell: bash
      run: |
        while IFS= read -r line; do
          if [[ "$line" =~ ^#.* ]] || [[ -z "$line" ]]; then
            continue
          fi
          echo "$line" >> $GITHUB_ENV
        done < .github/env/shared.env

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set App Service app settings
      run: |
        az webapp config appsettings set \
          --name "$AZURE_WEBAPP_NAME" \
          --resource-group "$RESOURCE_GROUP_NAME" \
          --settings \
            PORT=$APP_PORT \
            PYTHON_VERSION=$PYTHON_VERSION 

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        startup-command: >
            streamlit run streamlit_app.py
