name: "Deploy AI Trip Planner API"

on:
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - 'projects/ai-trip-planner/**'
  workflow_dispatch:

env:
  CODE_PATH: 'projects/ai-trip-planner'
  AZURE_WEBAPP_NAME: genaiapiv1
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # App Service expects source code
  PYTHON_VERSION: '3.11'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set App Service app settings
      shell: bash
      run: |
        az webapp config appsettings set \
          --name "$AZURE_WEBAPP_NAME" \
          --resource-group "AIML-RG" \
          --settings \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            PORT=8502 \
            PYTHON_VERSION=$PYTHON_VERSION \
            STARTUP_COMMAND="uvicorn main:app"

    - name: Deploy to Azure Web App using Oryx
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.CODE_PATH }}
